version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 396913744458.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker-compose build
      - docker tag backend 396913744458.dkr.ecr.ap-south-1.amazonaws.com/backend
      - docker tag frontend 396913744458.dkr.ecr.ap-south-1.amazonaws.com/frontend
  post_build:
    commands:
      - echo Pushing images...
      - docker push 396913744458.dkr.ecr.ap-south-1.amazonaws.com/backend
      - docker push 396913744458.dkr.ecr.ap-south-1.amazonaws.com/frontend
artifacts:
  files:
    - docker-compose.yml
