version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - AWS_REGION=ap-south-1
      - S3_BUCKET=video-bucket1234jan
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"